#ifndef CMIDID_IOCTL_H
#define CMIDID_IOCTL_H

#include <asm/ioctl.h>

#define CMIDID_CALIBRATE_MIN_TIME _IO(0, 0)
#define CMIDID_CALIBRATE_MAX_TIME _IO(0, 1)

#define CMIDID_VEL_CURVE_LINEAR _IO(0, 2)
#define CMIDID_VEL_CURVE_CONCAVE _IO(0, 3)
#define CMIDID_VEL_CURVE_CONVEX _IO(0, 4)
#define CMIDID_VEL_CURVE_SATURATED _IO(0, 5)

#endif